# Generated by Django 3.2.14 on 2022-08-17 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('favorites_1', models.CharField(choices=[('백엔드', '백엔드'), ('프론트엔드', '프론트엔드'), ('Andriod', 'Andriod'), ('iOS', 'iOS')], default='', max_length=200)),
                ('favorites_2', models.CharField(choices=[('백엔드', '백엔드'), ('프론트엔드', '프론트엔드'), ('Andriod', 'Andriod'), ('iOS', 'iOS')], default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('followings', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='media/button.png', upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
